[phases.setup]
nixPkgs = ["chromium", "libx11", "libxcomposite", "libxcursor", "libxdamage", "libxext", "libxfixes", "libxi", "libxrandr", "libxrender", "libxss", "libxtst", "ca-certificates", "fonts-liberation", "xdg-utils", "atk", "at-spi2-atk", "gtk3"]

[phases.install]
cmds = ["npm ci --only=production"]

[phases.build]
cmds = ["echo 'No build step required'"]

[start]
cmd = "node index.js" 