[phases.setup]
nixPkgs = ["nodejs", "chromium", "libnss3", "libatk1.0-0", "libatk-bridge2.0-0", "libcups2", "libgbm1", "libasound2", "libpangocairo-1.0-0", "libxss1", "libgtk-3-0", "libxshmfence1", "libglu1"]

[phases.install]
cmds = ["npm ci --only=production"]

[phases.build]
cmds = ["echo 'No build step required'"]

[start]
cmd = "node test-server.js" 