[phases.setup]
nixPkgs = ["nodejs", "chromium"]

[phases.install]
cmds = ["npm ci"]  # Remove --only=production

[phases.build]
cmds = ["npm run prebuild", "npm run build"]

[start]
cmd = "node test-server.js" 