[build]
builder = "nixpacks"

[deploy]
startCommand = "node index.js"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[deploy.envs]
NODE_ENV = "production" 